/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_twitter_university_exify_JHead */

#ifndef _Included_com_twitter_university_exify_JHead
#define _Included_com_twitter_university_exify_JHead
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_twitter_university_exify_JHead
 * Method:    getImageInfo
 * Signature: (Ljava/lang/String;)Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL Java_com_twitter_university_exify_JHead_getImageInfo
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_twitter_university_exify_JHead
 * Method:    getThumbnail
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_twitter_university_exify_JHead_getThumbnail
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
